apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: dummy-test
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: dummy-test
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/part-of: dummy-test
  ports:
    - name: http
      port: 8000
      targetPort: http
